### PR TITLE
Feature/host image

### PR DESCRIPTION
**Pull request by mohinderps**

### CODE REVIEW

**Comment by mohinderps** [comment]
Hey @agarrharr, I am not sure why build failed on Netlify. Can you help me with this?

**Comment by mohinderps** [comment]
Is it possible that the host object may not contain image ?

**Comment by mohinderps** [comment]
@agarrharr , I have added a check if the host image exists or not. Not having that check was causing the build failure.

**Comment by agarrharr** [comment]
Yes, it is possible that it doesn't exist.

It's looking good!
If there are more than 2 speakers, it isn't showing more than 2 images:

screen shot 2018-10-06 at 10 17 46 am

Also, could you move the speakers down below the timestamp?

**Comment by agarrharr** [comment]
Here is an example with 3 people and 5 people on GitHub.

screen shot 2018-10-06 at 10 37 43 am

screen shot 2018-10-06 at 10 37 59 am

**Comment by mohinderps** [comment]
Okay, will do.

**Comment by mohinderps** [comment]
So do we follow how github does with 5 images? That would make the last image difficult to see.

With my current implementation, half of all the image except first one will be visible.

**Comment by agarrharr** [comment]
That looks awesome! The reason GitHub hides them is because they could have an unlimited number of people, and also they do an animation when you hover.

**Pull request merged**
