### PR TITLE
Add logo to header

### PR DESCRIPTION
**Pull request by bersLucas**
firefox_2018-10-01_23-47-48

I'm not familiar enough with gatsby.js to change the favicon as well, but putting it in the root of your webserver works as well.

Related Issue:
https://github.com/orbitfm/orbit.fm/issues/107

### CODE REVIEW

**Comment by agarrharr** [comment]
Could you try adding some colors? You can get some ideas for colors from the current podcast cover art on the site.

**Comment by bersLucas** [comment]
Sure thing, do you mean adding colors to the logo or to the website in general?

**Comment by agarrharr** [comment]
Just to the logo.

**Comment by bersLucas** [comment]
firefox_2018-10-03_18-58-44
firefox_2018-10-03_18-58-56
firefox_2018-10-03_18-59-54
firefox_2018-10-03_19-00-37
firefox_2018-10-03_19-05-50

Here are a couple, let me know if any of them look nice or if I should change anything

**Comment by agarrharr** [comment]
2 and 4 look pretty good.

**Comment by bersLucas** [comment]
Changed it to the 2nd one.

**Pull request closed without merging**
